import './globals.css'
import { Inter } from 'next/font/google'
import { ServerAuthProvider } from '@/auth/server-auth-provider'
import ElementsDashboard from './ElementsDashboard'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SIJ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
     
     {children}
     
     
     
     </body>
      
    </html>
  )
}
     
     
       
