import './globals.css'
import { Inter } from 'next/font/google'
import { ServerAuthProvider } from '@/auth/server-auth-provider'
import ElementsDashboard from './ElementsDashboard'
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SIJ',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode, modal: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={inter.className}>

        {props.children}
        {props.modal}
     
 
     
     </body>
      
    </html>
  )
}
     
     
       

